src/js/controllers/WalletControllers.js
src/js/localisation/translations.js
src/js/services/WalletService.js
src/templates/wallet/wallet.tx-info.modal.html

- clear previous unctxs on each poll to handle txs that have been removed from mempool
- ensure confirmed txs are still updated

use updated WalletService from the mobile app repo;

---

src/templates/setup/setup.login.html

for LAUNCH_NEW_ACCOUNT as LAUNCH_EXISTING_ACCOUNT

setup.login.html: same style

---

src/js/app.js
src/js/controllers/ReceiveControllers.js
src/sass/_theme.scss
src/templates/receive/receive.address-lookup.html
src/templates/receive/receive.new-address.html

Please review and merge.
To test:
in bower.json, add the following change:
```
"dependencies": {
"blocktrail-sdk": "git@github.com:blocktrail/blocktrail-sdk-nodejs.git#da52ae2",
. . .
```
and then `bower install`

Address lookup in receive state with search

---

src/js/modules/setup/controllers/download-mobile-modal/download-mobile-modal.tpl.html
src/js/modules/setup/controllers/new-account/new-account.tpl.html
src/templates/buybtc/buybtc.buy.html
src/templates/send/dialog.send-confirm.html

Updated translations in templates to adapt to different linguistic typology.
Please review and merge.

Prepare templates for language updates

---

gulpfile.js
src/js/app.js
src/js/modules/core/configs/localisation/localisation.config.js
src/js/modules/core/services/localisation/localisation.provider.js

Enable new languages on web (japanese, german, korean, portuguese, arabic)

---

bower.json
src/js/controllers/WalletControllers.js
src/js/modules/core/constants/third-party-libraries/third-party-libraries.constant.js
src/js/modules/core/filters/bip39en/bip39en.filter.js
src/js/modules/core/services/sweeper/sweeper-service.factory.js
src/js/modules/wallet/controllers/settings/settings.ctrl.js
src/js/modules/wallet/controllers/settings/settings.tpl.html
src/js/modules/wallet/controllers/sweep-coins-modal/sweep-coins-modal.ctrl.js
src/js/modules/wallet/controllers/sweep-coins-modal/sweep-coins-modal.tpl.html

Please review and discuss.
I'm not sure where we should put the button yet.

Sweep generic mnemonic's

---

src/js/modules/setup/controllers/change-password/change-password.ctrl.js

Added more error dialogs when changing the password.
Please review and merge.

Enforce password strength check with error dialog

---

src/js/modules/core/services/sweeper/sweeper-service.factory.js
src/js/modules/wallet/controllers/sweep-coins-modal/sweep-coins-modal.ctrl.js

Fixes fee estimation being below the minrelayfee

Sweeper fee estimation

---

src/js/modules/core/services/password-recovery/password-recovery.factory.js
src/js/modules/setup/controllers/change-password/change-password.ctrl.js
src/js/modules/setup/controllers/forgot-password/forgot-password.ctrl.js

Prompt about upgraded wallet on recovery email request

---

src/js/controllers/SendControllers.js

Please review and merge. :)
Or discuss how to evaluate the error better, perhaps
`e instanceof Error && e.message === "XYZ"`
is to generic?

Fix amount error notification and no resume on "balance to low"

---

src/templates/common/footer.html

Please review, thanks. Needs translations from the same branch name as well.

Update ref links in footer

---

src/js/services/CurrencyServices.js

Please review, discuss and merge.

Add PLN, CAD, PHP to currencies, sort them with EUR, USD, CNY always on top

---

src/js/modules/core/services/sweeper/sweeper.service.js
src/js/modules/wallet/controllers/sweep-coins-modal/sweep-coins-modal.ctrl.js
src/js/modules/wallet/controllers/sweep-coins-modal/sweep-coins-modal.tpl.html

Please review, discuss and merge :)

Sweep too many inputs in multiple transactions (Sweeper)

---

src/js/modules/setup/controllers/wallet-backup/wallet-backup.ctrl.js

Signup button get's disabled as the wallet list was not fetched yet, therefore throws.

Fix issue with signup backup download button being disabled after DL

---

src/js/modules/wallet/controllers/send-confirm-modal/send-confirm-modal.ctrl.js

Not sure where this came from, it was there before the recent code moves..

randomize change index

---

src/js/modules/core/services/notifications/notifications.service.js
src/js/modules/core/services/settings/settings.service.js
src/js/modules/wallet/configs/wallet-states/wallet-states.config.js
src/js/modules/wallet/controllers/payment-uri/payment-uri.ctrl.js
src/js/modules/wallet/controllers/payment-uri/payment-uri.tpl.html
src/js/modules/wallet/controllers/send/send.ctrl.js
src/js/modules/wallet/controllers/settings/settings.ctrl.js
src/js/modules/wallet/controllers/settings/settings.tpl.html
src/js/modules/wallet/controllers/wallet-summary/wallet-summary.ctrl.js
src/js/modules/wallet/controllers/wallet/wallet.tpl.html

Please test, review and merge
I recommend to drop this into wallet summary for testing
`    <a href="bitcoin:YOUR_BTC_ADDR?amount=YOUR_FAV_AMOUNT">
<button class="btn btn-warning">TEST LINK</button>
</a>`

Bitcoin URI handling and registering with proper attention to BCC / BTC

---

src/js/modules/wallet/controllers/send/send.ctrl.js

Fix fee loading on empty balance wallets

---

README.md

http://www.english-for-students.com/Incase.html :)

fix incase typo

---

src/js/modules/setup/controllers/wrapper/wrapper.tpl.html

Added alert banner warning users about hardfork.

added warning for users about bch hardfork

---

src/js/modules/core/services/settings/settings.service.js
src/js/modules/wallet/controllers/wallet-summary/wallet-summary.ctrl.js
src/js/modules/wallet/controllers/wallet-summary/wallet-summary.tpl.html
src/js/modules/wallet/directives/app-bcc-fork-warning/app-bcc-fork-warning.directive.js
src/js/modules/wallet/directives/app-bcc-fork-warning/app-bcc-fork-warning.tpl.html

Additional Bitcoin Cash hardfork in-wallet warning

---

.circleci/config.yml
README.md
appconfig.default.json
gulpfile.js
src/index.html
src/js/modules/setup/services/login/login.service.js
src/js/modules/setup/services/new-account/new-account.service.js

* build via CircleCi
* add recaptcha

build via CircleCi

---

.circleci/config.yml

upgrade captcha keys

---

src/js/modules/core/services/password-recovery/password-recovery.service.js
src/js/modules/setup/controllers/forgot-password/forgot-password.ctrl.js

* add recaptcha for forgot password

add recaptcha for forgot password

---

.circleci/config.yml

* remove Facebook, Quora, less baggage

remove FB,Quora

---

src/index.html

optimize recaptcha
